"""
健康档案路由
"""
from fastapi import APIRouter, HTTPException
from loguru import logger
from typing import List, Dict, Any
from datetime import datetime

from app.models.user import (
    HealthProfile, ProfileConfirmRequest,
    MemberProfile, VitalSigns, HealthHabits,
    MemberCreateRequest
)
from app.services.profile_service import profile_service, member_profile_service, health_history_service, health_records_service

router = APIRouter()


@router.get("/{user_id}")
async def get_profile(user_id: str):
    """
    获取健康档案

    Args:
        user_id: 用户ID

    Returns:
        dict: 健康档案
    """
    try:
        profile = profile_service.get_profile(user_id)

        return {
            "code": 0,
            "data": profile.model_dump()
        }

    except Exception as e:
        logger.error(f"获取健康档案失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.put("/{user_id}")
async def update_profile(user_id: str, profile: HealthProfile):
    """
    更新健康档案

    Args:
        user_id: 用户ID
        profile: 健康档案

    Returns:
        dict: 更新结果
    """
    try:
        profile.user_id = user_id
        profile_service.save_profile(profile)
        logger.info(f"更新用户 {user_id} 的健康档案")

        return {
            "code": 0,
            "message": "更新成功",
            "data": profile.model_dump()
        }

    except Exception as e:
        logger.error(f"更新健康档案失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/{user_id}/confirm")
async def confirm_profile_update(user_id: str, updates: ProfileConfirmRequest):
    """
    确认档案更新（用于强特征确认）

    Args:
        user_id: 用户ID
        updates: 待确认的更新

    Returns:
        dict: 确认结果
    """
    try:
        profile = profile_service.confirm_updates(user_id, updates.model_dump())
        logger.info(f"用户 {user_id} 确认档案更新: {updates}")

        return {
            "code": 0,
            "message": "确认成功",
            "data": profile.model_dump()
        }

    except Exception as e:
        logger.error(f"确认档案更新失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{user_id}/pending")
async def get_pending_confirmations(user_id: str):
    """
    获取待确认档案更新

    Args:
        user_id: 用户ID

    Returns:
        dict: 待确认列表
    """
    try:
        profile = profile_service.get_profile(user_id)
        return {
            "code": 0,
            "data": {
                "user_id": user_id,
                "pending_confirmations": profile.pending_confirmations
            }
        }
    except Exception as e:
        logger.error(f"获取待确认档案失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


# ============ 成员档案管理接口 ============

@router.get("/{user_id}/members")
async def get_members(user_id: str):
    """
    获取用户的所有家庭成员

    Args:
        user_id: 用户ID

    Returns:
        dict: 成员列表
    """
    try:
        members = member_profile_service.get_members(user_id)
        return {
            "code": 0,
            "data": {
                "user_id": user_id,
                "members": members,
                "total": len(members)
            }
        }
    except Exception as e:
        logger.error(f"获取成员列表失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/members/{member_id}")
async def get_member(member_id: str):
    """
    获取单个成员详细信息

    Args:
        member_id: 成员ID

    Returns:
        dict: 成员详细信息
    """
    try:
        member = member_profile_service.get_member(member_id)
        if not member:
            raise HTTPException(status_code=404, detail="成员不存在")

        return {
            "code": 0,
            "data": member
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"获取成员详情失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/{user_id}/members")
async def create_member(user_id: str, request: MemberCreateRequest):
    """
    创建新家庭成员
    """
    try:
        # 1. 创建基础档案
        member = MemberProfile(
            id="",  # ID will be generated by service
            user_id=user_id,
            name=request.name,
            relationship=request.relationship,
            id_card_type=request.id_card_type,
            id_card_number=request.id_card_number,
            gender=request.gender,
            birth_date=request.birth_date,
            phone=request.phone,
            avatar_url=request.avatar_url
        )

        member_id = member_profile_service.create_member(member)
        logger.info(f"用户 {user_id} 创建成员 {member_id}")

        # 2. 保存体征信息
        if request.height_cm is not None and request.weight_kg is not None:
            vital_signs = VitalSigns(
                member_id=member_id,
                height_cm=request.height_cm,
                weight_kg=request.weight_kg,
                blood_pressure_systolic=request.blood_pressure_systolic,
                blood_pressure_diastolic=request.blood_pressure_diastolic,
                blood_sugar=request.blood_sugar,
                blood_sugar_type=request.blood_sugar_type
            )
            member_profile_service.upsert_vital_signs(vital_signs)

        # 3. 保存生活习惯
        if any([request.diet_habit, request.exercise_habit, request.sleep_quality,
                request.smoking_drinking, request.sedentary_habit, request.mental_status]):
            habits = HealthHabits(
                member_id=member_id,
                diet_habit=request.diet_habit,
                exercise_habit=request.exercise_habit,
                sleep_quality=request.sleep_quality,
                smoking_drinking=request.smoking_drinking,
                sedentary_habit=request.sedentary_habit,
                mental_status=request.mental_status
            )
            member_profile_service.upsert_health_habits(habits)

        return {
            "code": 0,
            "message": "创建成功",
            "data": {
                "member_id": member_id,
                **member.model_dump()
            }
        }
    except Exception as e:
        logger.error(f"创建成员失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.put("/members/{member_id}")
async def update_member(member_id: str, member: MemberProfile):
    """
    更新成员信息

    Args:
        member_id: 成员ID
        member: 成员信息

    Returns:
        dict: 更新结果
    """
    try:
        success = member_profile_service.update_member(member_id, member)
        if not success:
            raise HTTPException(status_code=404, detail="成员不存在")

        logger.info(f"更新成员 {member_id} 信息")
        return {
            "code": 0,
            "message": "更新成功",
            "data": member.model_dump()
        }
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"更新成员失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.delete("/members/{member_id}")
async def delete_member(member_id: str):
    """
    删除成员

    Args:
        member_id: 成员ID

    Returns:
        dict: 删除结果
    """
    try:
        success = member_profile_service.delete_member(member_id)
        if not success:
            raise HTTPException(status_code=404, detail="成员不存在")

        logger.info(f"删除成员 {member_id}")
        return {
            "code": 0,
            "message": "删除成功",
            "data": {"member_id": member_id, "deleted": True}
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"删除成员失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.put("/members/{member_id}/vital-signs")
async def update_vital_signs(member_id: str, vital_signs: VitalSigns):
    """
    更新成员体征信息

    Args:
        member_id: 成员ID
        vital_signs: 体征信息

    Returns:
        dict: 更新结果
    """
    try:
        vital_signs.member_id = member_id
        member_profile_service.upsert_vital_signs(vital_signs)

        return {
            "code": 0,
            "message": "体征信息已更新",
            "data": vital_signs.model_dump()
        }
    except Exception as e:
        logger.error(f"更新体征信息失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.put("/members/{member_id}/habits")
async def update_health_habits(member_id: str, habits: HealthHabits):
    """
    更新成员生活习惯

    Args:
        member_id: 成员ID
        habits: 生活习惯

    Returns:
        dict: 更新结果
    """
    try:
        habits.member_id = member_id
        member_profile_service.upsert_health_habits(habits)

        return {
            "code": 0,
            "message": "生活习惯已更新",
            "data": habits.model_dump()
        }
    except Exception as e:
        logger.error(f"更新生活习惯失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


# ============ 健康史管理接口 ============

@router.get("/members/{member_id}/history")
async def get_member_history(member_id: str):
    """
    获取成员健康史摘要

    Args:
        member_id: 成员ID

    Returns:
        dict: 健康史摘要
    """
    try:
        summary = health_history_service.get_history_summary(member_id)
        return {
            "code": 0,
            "data": {
                "member_id": member_id,
                **summary
            }
        }
    except Exception as e:
        logger.error(f"获取健康史失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/members/{member_id}/history/allergy")
async def get_allergy_history(member_id: str):
    """获取过敏史"""
    try:
        history = health_history_service.get_allergy_history(member_id)
        return {
            "code": 0,
            "data": {
                "member_id": member_id,
                "allergy_history": history,
                "total": len(history)
            }
        }
    except Exception as e:
        logger.error(f"获取过敏史失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/members/{member_id}/history/allergy")
async def add_allergy(member_id: str, data: Dict[str, Any]):
    """添加过敏记录"""
    try:
        record_id = health_history_service.add_allergy(
            member_id=member_id,
            allergen=data.get("allergen"),
            reaction=data.get("reaction"),
            severity=data.get("severity", "mild"),
            date=data.get("date")
        )
        return {
            "code": 0,
            "message": "添加成功",
            "data": {"record_id": record_id}
        }
    except Exception as e:
        logger.error(f"添加过敏史失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/members/{member_id}/history/medical")
async def get_medical_history(member_id: str):
    """获取既往病史"""
    try:
        history = health_history_service.get_medical_history(member_id)
        return {
            "code": 0,
            "data": {
                "member_id": member_id,
                "medical_history": history,
                "total": len(history)
            }
        }
    except Exception as e:
        logger.error(f"获取既往病史失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/members/{member_id}/history/medical")
async def add_medical_history(member_id: str, data: Dict[str, Any]):
    """添加既往病史"""
    try:
        record_id = health_history_service.add_medical_history(
            member_id=member_id,
            condition=data.get("condition"),
            diagnosis_date=data.get("diagnosis_date"),
            treatment=data.get("treatment"),
            status=data.get("status", "ongoing"),
            hospital=data.get("hospital")
        )
        return {
            "code": 0,
            "message": "添加成功",
            "data": {"record_id": record_id}
        }
    except Exception as e:
        logger.error(f"添加既往病史失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/members/{member_id}/history/family")
async def get_family_history(member_id: str):
    """获取家族病史"""
    try:
        history = health_history_service.get_family_history(member_id)
        return {
            "code": 0,
            "data": {
                "member_id": member_id,
                "family_history": history,
                "total": len(history)
            }
        }
    except Exception as e:
        logger.error(f"获取家族病史失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/members/{member_id}/history/family")
async def add_family_history(member_id: str, data: Dict[str, Any]):
    """添加家族病史"""
    try:
        record_id = health_history_service.add_family_history(
            member_id=member_id,
            condition=data.get("condition"),
            relative=data.get("relative")
        )
        return {
            "code": 0,
            "message": "添加成功",
            "data": {"record_id": record_id}
        }
    except Exception as e:
        logger.error(f"添加家族病史失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/members/{member_id}/history/medication")
async def get_medication_history(member_id: str):
    """获取用药史"""
    try:
        history = health_history_service.get_medication_history(member_id)
        return {
            "code": 0,
            "data": {
                "member_id": member_id,
                "medication_history": history,
                "total": len(history)
            }
        }
    except Exception as e:
        logger.error(f"获取用药史失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/members/{member_id}/history/medication")
async def add_medication_history(member_id: str, data: Dict[str, Any]):
    """添加用药史"""
    try:
        record_id = health_history_service.add_medication_history(
            member_id=member_id,
            drug_name=data.get("drug_name"),
            dosage=data.get("dosage"),
            frequency=data.get("frequency"),
            start_date=data.get("start_date"),
            end_date=data.get("end_date"),
            reason=data.get("reason")
        )
        return {
            "code": 0,
            "message": "添加成功",
            "data": {"record_id": record_id}
        }
    except Exception as e:
        logger.error(f"添加用药史失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


# ============ 健康记录管理接口 ============

@router.get("/members/{member_id}/records/summary")
async def get_records_summary(member_id: str):
    """获取健康记录摘要"""
    try:
        summary = health_records_service.get_records_summary(member_id)
        return {
            "code": 0,
            "data": {
                "member_id": member_id,
                **summary
            }
        }
    except Exception as e:
        logger.error(f"获取健康记录摘要失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/members/{member_id}/records/consultation")
async def add_consultation_record(member_id: str, data: Dict[str, Any]):
    """添加问诊记录"""
    try:
        record_id = health_records_service.add_consultation(
            member_id=member_id,
            date=data.get("date", datetime.now().strftime("%Y-%m-%d")),
            summary=data.get("summary"),
            doctor=data.get("doctor"),
            hospital=data.get("hospital"),
            department=data.get("department")
        )
        return {
            "code": 0,
            "message": "添加成功",
            "data": {"record_id": record_id}
        }
    except Exception as e:
        logger.error(f"添加问诊记录失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/members/{member_id}/records/prescription")
async def add_prescription_record(member_id: str, data: Dict[str, Any]):
    """添加处方记录"""
    try:
        record_id = health_records_service.add_prescription(
            member_id=member_id,
            date=data.get("date", datetime.now().strftime("%Y-%m-%d")),
            drugs=data.get("drugs", []),
            doctor=data.get("doctor"),
            hospital=data.get("hospital"),
            diagnosis=data.get("diagnosis")
        )
        return {
            "code": 0,
            "message": "添加成功",
            "data": {"record_id": record_id}
        }
    except Exception as e:
        logger.error(f"添加处方记录失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/members/{member_id}/records/appointment")
async def add_appointment_record(member_id: str, data: Dict[str, Any]):
    """添加挂号记录"""
    try:
        record_id = health_records_service.add_appointment(
            member_id=member_id,
            date=data.get("date"),
            department=data.get("department"),
            hospital=data.get("hospital"),
            doctor=data.get("doctor")
        )
        return {
            "code": 0,
            "message": "添加成功",
            "data": {"record_id": record_id}
        }
    except Exception as e:
        logger.error(f"添加挂号记录失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/members/{member_id}/records/document")
async def add_document_record(member_id: str, data: Dict[str, Any]):
    """添加病历存档"""
    try:
        record_id = health_records_service.add_document(
            member_id=member_id,
            date=data.get("date", datetime.now().strftime("%Y-%m-%d")),
            doc_type=data.get("type", "report"),
            title=data.get("title"),
            file_url=data.get("file_url"),
            description=data.get("description"),
            hospital=data.get("hospital")
        )
        return {
            "code": 0,
            "message": "添加成功",
            "data": {"record_id": record_id}
        }
    except Exception as e:
        logger.error(f"添加病历存档失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/members/{member_id}/records/checkup")
async def add_checkup_record(member_id: str, data: Dict[str, Any]):
    """添加体检检验记录"""
    try:
        record_id = health_records_service.add_checkup(
            member_id=member_id,
            date=data.get("date", datetime.now().strftime("%Y-%m-%d")),
            checkup_type=data.get("type"),
            hospital=data.get("hospital"),
            summary=data.get("summary"),
            results=data.get("results"),
            abnormal_items=data.get("abnormal_items", [])
        )
        return {
            "code": 0,
            "message": "添加成功",
            "data": {"record_id": record_id}
        }
    except Exception as e:
        logger.error(f"添加体检检验记录失败: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))
